FROM registry.access.redhat.com/ubi10/python-312-minimal:latest
ADD server.py server.py
ADD requirements.txt requirements.txt
ADD Brand Brand
RUN pip install -r requirements.txt
EXPOSE 5000
ENTRYPOINT [ "python", "server.py" ]